version: '3.8'

services:  
  alpha:
    image: node:14
    working_dir: /srv/alpha
    entrypoint: 
      - /bin/sh
      - /srv/alpha/entrypoint.sh
    ports:
      - "3000"
    volumes:
      - ./alpha:/srv/alpha
    depends_on: 
      - nginx

  setup_one:
    image: node:14
    working_dir: /srv/setup_one
    entrypoint: 
      - /bin/sh
      - /srv/setup_one/entrypoint.sh
    ports:
      - "3000"
    volumes:
      - ./setup_one:/srv/setup_one
    depends_on: 
      - nginx

  setup_two:
    image: node:14
    working_dir: /srv/setup_two
    entrypoint: 
      - /bin/sh
      - /srv/setup_two/entrypoint.sh
    ports:
      - "3000"
    volumes:
      - ./setup_two:/srv/setup_two
    depends_on: 
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      